name: "Frogbot Scan Repository"
on: workflow_dispatch
#  workflow_dispatch:
#  schedule:
#    - cron: "0 0 * * *"
permissions:
  contents: write
  pull-requests: write
  security-events: write
jobs:
  scan-repository:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # The repository scanning will be triggered periodically on the following branches.
        branch: [ "main" ]
    steps:
      - uses: jfrog/frogbot@v2
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          #JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #JF_GIT_BASE_BRANCH: ${{ matrix.branch }}
